#ifndef LOAD_ASSET_H
#define LOAD_ASSET_H
std::string GetAssetPath(const char* assetName) 
{
  // Generated by CMake to return absolute path on disk.
  return std::string("C:/Users/Traver/Desktop/GMD-202/gpr200-fa2024-template-Traver/assignments/Assignment2_Indicies\\assets\\") + assetName;
}
#endif
